eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    non-secure-port: 80
  client:
    service-url:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka
spring:
  jpa:
    generate-ddl: true